/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as DiagnosisHistoryVehicleIdRouteImport } from './routes/diagnosis-history/$vehicleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosisHistoryVehicleIdRoute =
  DiagnosisHistoryVehicleIdRouteImport.update({
    id: '/diagnosis-history/$vehicleId',
    path: '/diagnosis-history/$vehicleId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnosis-history/$vehicleId': typeof DiagnosisHistoryVehicleIdRoute
  '/home': typeof HomeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnosis-history/$vehicleId': typeof DiagnosisHistoryVehicleIdRoute
  '/home': typeof HomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagnosis-history/$vehicleId': typeof DiagnosisHistoryVehicleIdRoute
  '/home/': typeof HomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/diagnosis-history/$vehicleId' | '/home'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/diagnosis-history/$vehicleId' | '/home'
  id: '__root__' | '/' | '/diagnosis-history/$vehicleId' | '/home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagnosisHistoryVehicleIdRoute: typeof DiagnosisHistoryVehicleIdRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnosis-history/$vehicleId': {
      id: '/diagnosis-history/$vehicleId'
      path: '/diagnosis-history/$vehicleId'
      fullPath: '/diagnosis-history/$vehicleId'
      preLoaderRoute: typeof DiagnosisHistoryVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagnosisHistoryVehicleIdRoute: DiagnosisHistoryVehicleIdRoute,
  HomeIndexRoute: HomeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
